### ISSUE TITLE
Уведомления

### ISSUE THREAD

**Issue by Fursanov** [l1arvakar/ToDoList#1]
![Снимок экрана от 2024-12-30 11-40-36](https://github.com/user-attachments/assets/b83e4b48-11c9-4ce9-927b-b203b0a62741)

https://github.com/l1arvakar/ToDoList/blob/abbfc802ef7e7292fd252a31c93a569768dd23ba/frontend/frontend/src/pages/Registration.jsx#L54-L58

Для уведомлений лучше использовать Toast, как в коде ниже. 

https://github.com/l1arvakar/ToDoList/blob/abbfc802ef7e7292fd252a31c93a569768dd23ba/frontend/frontend/src/pages/TasksList.jsx#L27

**Comment by l1arvakar** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/649a038f-5264-4852-8c38-c88cb7927b65)
![Screenshot_2](https://github.com/user-attachments/assets/88438c2f-fa68-4b9d-be5d-efd22702a5b3)
![Screenshot_3](https://github.com/user-attachments/assets/4104f24a-761d-4808-ab61-d5b99d16915c)
Вывод уведомлений об ошибках и успехе везде изменён на toast
