### ISSUE TITLE
Описание задачи

### ISSUE THREAD

**Issue by Fursanov** [l1arvakar/ToDoList#2]
![Снимок экрана от 2024-12-30 11-18-14](https://github.com/user-attachments/assets/ee34c324-aec0-4053-9a55-1695148489f5)

Фронт съезжает при вводе в поле описание задачи максимального количества символов без пробелов. Раз возможность такая дана, значит должно работать нормально.

**Comment by l1arvakar** [comment]
![image](https://github.com/user-attachments/assets/92f78b0e-4edb-458a-998c-51a6cdb4764a)
Создано ограничение по размеру ячейки, при большем размере теска он заканчивается многоточием
