### ISSUE TITLE
Создание задачи

### ISSUE THREAD

**Issue by Fursanov** [l1arvakar/ToDoList#3]
Селектор готовности задачи отображается некорректно, фон отрисовывается ниже по слою чем другие поля ввода.

![Снимок экрана от 2024-12-30 11-15-57](https://github.com/user-attachments/assets/9b73a78f-1ba4-44d9-98e4-1a767494a772)

**Comment by l1arvakar** [comment]
![image](https://github.com/user-attachments/assets/2c73177a-e1a6-4d9b-83d6-29567fa1f21d)
Меню dropdown элемента теперь отображается выше других полей
