### ISSUE TITLE
Кнопка возврата 

### ISSUE THREAD

**Issue by Fursanov** [l1arvakar/ToDoList#4]
![Снимок экрана от 2024-12-30 11-15-50](https://github.com/user-attachments/assets/e0aec162-7ca5-40a6-85b7-092c7173d63f)

Кнопка возврата реализована надписью.

**Comment by l1arvakar** [comment]
![image](https://github.com/user-attachments/assets/4fc6ce1f-71f3-4d48-bbcc-532cc0b10922)
Реализация кнопки возврата изменена на элемент Button
